"""MPS drop-in for the ``flash_attn_2_cuda`` C extension (FA2 backend ABI).

``flash_attn/flash_attn_interface.py`` binds its entire compute backend to a single
module named ``flash_attn_gpu`` and calls exactly five functions on it, all
positionally: ``fwd``, ``varlen_fwd``, ``bwd``, ``varlen_bwd``, ``fwd_kvcache``.
This module mirrors that ABI for Apple Silicon by delegating to the shared,
parity-tested MPS core (``flash_attn/mps/core.py``) and the varlen driver
(``flash_attn/mps/varlen.py``). See docs/apple_silicon/MPS_STATUS.md for the
feature matrix and performance caveats.

Conventions shared by all five functions (matching the C extension):

- Tensor layout is ``(batch, seqlen, nheads, headdim)`` (or ``(total, nheads,
  headdim)`` for varlen), last dim contiguous.
- ``out`` / ``dq`` / ``dk`` / ``dv`` arguments are optional preallocated output
  tensors; when ``None`` the backend allocates them. **``bwd``/``varlen_bwd``
  fill ``dq``/``dk``/``dv`` IN PLACE** — the FA2 interface reads gradients
  through those tensors (sometimes through non-contiguous views like
  ``dkv[:, :, 0]``) and only consumes ``softmax_d`` from the return value.
- ``gen`` is an optional ``torch.Generator`` for dropout RNG; the interface always
  passes ``None``.
- ``softmax_lse`` is float32 with shape ``(batch, nheads, seqlen_q)`` (dense) or
  ``(nheads, total_q)`` (varlen).
- Window sizes use the FA2 encoding: **any negative value means "infinite" on
  that side** (csrc/flash_attn/flash_api.cpp:141-142). The core uses ``None``
  for infinite and treats negative windows as genuinely negative, so the
  translation happens here and only here.
- ``softmax_lse`` for fully-masked rows is ``+inf``, matching the FA2 CUDA
  kernel's non-split path (csrc/flash_attn/src/softmax.h:180). The shared core
  natively emits ``-inf`` (the FA4/CuTe convention,
  flash_attn/cute/softmax.py:225); this adapter flips the sign.

Unsupported features raise ``NotImplementedError`` naming the feature — never
a wrong number. Notably ``dropout_p > 0``: FA2's dropout mask is generated by
the CUDA Philox RNG inside the kernel and reproduced from ``rng_state`` in the
backward. There is no way to bit-match that RNG on MPS, and a torch-side
dropout whose forward mask cannot be reproduced exactly in the recompute-based
backward would produce silently wrong gradients — the exact failure mode this
port exists to prevent. So dropout raises instead of lying.

Perf-only knobs (``num_splits``, ``deterministic``, ``zero_tensors``,
``rotary_interleaved`` without rotary) are accepted and ignored.
"""

import torch

from flash_attn.mps.core import mps_flash_attn_func
from flash_attn.mps.varlen import mps_flash_attn_varlen

_INF = float("inf")
_NEG_INF = float("-inf")


def _unsupported(feature, hint=""):
    raise NotImplementedError(
        f"flash_attn MPS backend (FA2 ABI): {feature} is not supported on Apple Silicon. "
        f"{hint}See docs/apple_silicon/MPS_STATUS.md for the feature matrix."
    )


def _check_dropout(dropout_p):
    if dropout_p is not None and dropout_p > 0.0:
        _unsupported(
            "dropout (dropout_p > 0)",
            "FA2 dropout uses the CUDA Philox RNG inside the kernel; it cannot be "
            "bit-matched on MPS, and an unreproducible mask would silently corrupt "
            "the recompute-based backward. Set dropout_p=0.0. ",
        )


def _window(window_size_left, window_size_right):
    """FA2 window encoding (negative == infinite) -> core encoding (None == infinite)."""
    return (
        None if window_size_left is None or window_size_left < 0 else window_size_left,
        None if window_size_right is None or window_size_right < 0 else window_size_right,
    )


def _flip_lse_inf(lse):
    """Core emits -inf for fully-masked rows; the FA2 CUDA contract is +inf."""
    return lse.masked_fill_(lse == _NEG_INF, _INF)


def _empty_aux(q):
    S_dmask = torch.empty((0,), dtype=q.dtype, device=q.device)
    rng_state = torch.zeros((2,), dtype=torch.int64, device=q.device)
    return S_dmask, rng_state


def _fill_out(out, out_computed):
    if out is None:
        return out_computed
    out.copy_(out_computed)
    return out


def _round_multiple(x, m):
    return (x + m - 1) // m * m


def _softmax_d_dense(dout, out, seqlen_q):
    """D = rowsum(dout * out), fp32, (batch, nheads, seqlen_q_rounded)."""
    batch, _, nheads, _ = out.shape
    d = (dout.float() * out.float()).sum(dim=-1).transpose(1, 2)  # (b, h, sq)
    padded = torch.zeros(
        (batch, nheads, _round_multiple(seqlen_q, 128)),
        dtype=torch.float32,
        device=out.device,
    )
    padded[:, :, :seqlen_q] = d
    return padded


def _softmax_d_varlen(dout, out, batch):
    """D = rowsum(dout * out), fp32, (nheads, total_q + 128 * batch) (CUDA rounding)."""
    total_q, nheads, _ = out.shape
    d = (dout.float() * out.float()).sum(dim=-1).transpose(0, 1)  # (h, total_q)
    padded = torch.zeros((nheads, total_q + 128 * batch), dtype=torch.float32, device=out.device)
    padded[:, :total_q] = d
    return padded


def fwd(
    q,
    k,
    v,
    out,
    alibi_slopes,
    dropout_p,
    softmax_scale,
    causal,
    window_size_left,
    window_size_right,
    softcap,
    return_softmax,
    gen,
):
    """Dense forward. Mirrors ``flash_attn_2_cuda.fwd``.

    Called from ``_flash_attn_forward`` (flash_attn_interface.py).

    Returns:
        (out, softmax_lse, S_dmask, rng_state)
        - out: (batch, seqlen_q, nheads, headdim), dtype of q
        - softmax_lse: (batch, nheads, seqlen_q), float32, +inf on fully-masked rows
        - S_dmask: empty tensor (only meaningful with dropout, which raises)
        - rng_state: (2,) int64 dummy (dropout is unsupported)
    """
    _check_dropout(dropout_p)
    if return_softmax:
        _unsupported("return_attn_probs / S_dmask (return_softmax=True)")
    with torch.no_grad():
        # Split path (Phase 3b): SDPA computes out at Apple's fused speed and
        # a streaming fp32 pass computes the lse this ABI is obliged to
        # return; softcap/ALiBi fall back to the chunked core internally.
        out_c, lse = mps_flash_attn_func(
            q,
            k,
            v,
            softmax_scale=softmax_scale,
            causal=causal,
            window_size=_window(window_size_left, window_size_right),
            softcap=softcap,
            alibi_slopes=alibi_slopes,
            return_lse=True,
        )
        lse = _flip_lse_inf(lse)
    S_dmask, rng_state = _empty_aux(q)
    return _fill_out(out, out_c), lse, S_dmask, rng_state


def varlen_fwd(
    q,
    k,
    v,
    out,
    cu_seqlens_q,
    cu_seqlens_k,
    seqused_k,
    leftpad_k,
    block_table,
    alibi_slopes,
    max_seqlen_q,
    max_seqlen_k,
    dropout_p,
    softmax_scale,
    zero_tensors,
    causal,
    window_size_left,
    window_size_right,
    softcap,
    return_softmax,
    gen,
    num_splits,
):
    """Variable-length forward. Mirrors ``flash_attn_2_cuda.varlen_fwd``.

    Called from ``_flash_attn_varlen_forward`` (flash_attn_interface.py).
    ``q``/``k``/``v`` are packed as (total_tokens, nheads, headdim) with boundaries
    given by ``cu_seqlens_q``/``cu_seqlens_k`` (int32, (batch + 1,)).

    Returns:
        (out, softmax_lse, S_dmask, rng_state)
        - out: (total_q, nheads, headdim), dtype of q
        - softmax_lse: (nheads, total_q), float32, +inf on fully-masked rows
        - S_dmask, rng_state: as in ``fwd``
    """
    _check_dropout(dropout_p)
    if return_softmax:
        _unsupported("return_attn_probs / S_dmask (return_softmax=True)")
    if block_table is not None:
        _unsupported("paged KV cache (block_table)")
    if leftpad_k is not None:
        _unsupported("leftpad_k in varlen_fwd")
    with torch.no_grad():
        out_c, lse = mps_flash_attn_varlen(
            q,
            k,
            v,
            cu_seqlens_q=cu_seqlens_q,
            cu_seqlens_k=cu_seqlens_k,
            seqused_k=seqused_k,
            softmax_scale=softmax_scale,
            causal=causal,
            window_size=_window(window_size_left, window_size_right),
            softcap=softcap,
            alibi_slopes=alibi_slopes,
        )
        lse = _flip_lse_inf(lse)
    S_dmask, rng_state = _empty_aux(q)
    return _fill_out(out, out_c), lse, S_dmask, rng_state


def bwd(
    dout,
    q,
    k,
    v,
    out,
    softmax_lse,
    dq,
    dk,
    dv,
    alibi_slopes,
    dropout_p,
    softmax_scale,
    causal,
    window_size_left,
    window_size_right,
    softcap,
    deterministic,
    gen,
    rng_state,
):
    """Dense backward. Mirrors ``flash_attn_2_cuda.bwd``.

    Called from ``_flash_attn_backward`` (flash_attn_interface.py). ``dq``/``dk``/
    ``dv`` are preallocated by the caller and are filled IN PLACE (the caller
    reads gradients through those tensors; only ``softmax_d`` is consumed from
    the return value).

    Implementation: recompute + ``torch.autograd.grad`` over the shared core
    (flash-attention recomputes in its backward too — this is the same math,
    just not fused). ``softmax_lse``/``rng_state`` are not needed for that and
    are ignored.

    Returns:
        (dq, dk, dv, softmax_d)
        - dq: (batch, seqlen_q, nheads, headdim)
        - dk, dv: (batch, seqlen_k, nheads_k, headdim)
        - softmax_d: (batch, nheads, seqlen_q_rounded), float32,
          rowsum(dout * out) zero-padded to a multiple of 128
    """
    _check_dropout(dropout_p)
    if dq is None:
        dq = torch.empty_like(q)
    if dk is None:
        dk = torch.empty_like(k)
    if dv is None:
        dv = torch.empty_like(v)
    seqlen_q, seqlen_k = q.shape[1], k.shape[1]
    if seqlen_q == 0 or seqlen_k == 0:
        dq.zero_()
        dk.zero_()
        dv.zero_()
        return dq, dk, dv, _softmax_d_dense(dout, out, seqlen_q)
    q_l = q.detach().requires_grad_()
    k_l = k.detach().requires_grad_()
    v_l = v.detach().requires_grad_()
    with torch.enable_grad():
        out_r, _ = mps_flash_attn_func(
            q_l,
            k_l,
            v_l,
            softmax_scale=softmax_scale,
            causal=causal,
            window_size=_window(window_size_left, window_size_right),
            softcap=softcap,
            alibi_slopes=alibi_slopes,
            return_lse=False,
        )
    dq_c, dk_c, dv_c = torch.autograd.grad(out_r, (q_l, k_l, v_l), dout)
    dq.copy_(dq_c)
    dk.copy_(dk_c)
    dv.copy_(dv_c)
    return dq, dk, dv, _softmax_d_dense(dout, out, seqlen_q)


def varlen_bwd(
    dout,
    q,
    k,
    v,
    out,
    softmax_lse,
    dq,
    dk,
    dv,
    cu_seqlens_q,
    cu_seqlens_k,
    alibi_slopes,
    max_seqlen_q,
    max_seqlen_k,
    dropout_p,
    softmax_scale,
    zero_tensors,
    causal,
    window_size_left,
    window_size_right,
    softcap,
    deterministic,
    gen,
    rng_state,
):
    """Variable-length backward. Mirrors ``flash_attn_2_cuda.varlen_bwd``.

    Called from ``_flash_attn_varlen_backward`` (flash_attn_interface.py).
    ``dq``/``dk``/``dv`` are filled IN PLACE, as in ``bwd``.

    Returns:
        (dq, dk, dv, softmax_d)
        - dq: (total_q, nheads, headdim)
        - dk, dv: (total_k, nheads_k, headdim)
        - softmax_d: (nheads, total_q + 128 * batch), float32
    """
    _check_dropout(dropout_p)
    if dq is None:
        dq = torch.empty_like(q)
    if dk is None:
        dk = torch.empty_like(k)
    if dv is None:
        dv = torch.empty_like(v)
    batch = cu_seqlens_q.numel() - 1
    q_l = q.detach().requires_grad_()
    k_l = k.detach().requires_grad_()
    v_l = v.detach().requires_grad_()
    with torch.enable_grad():
        out_r, _ = mps_flash_attn_varlen(
            q_l,
            k_l,
            v_l,
            cu_seqlens_q=cu_seqlens_q,
            cu_seqlens_k=cu_seqlens_k,
            softmax_scale=softmax_scale,
            causal=causal,
            window_size=_window(window_size_left, window_size_right),
            softcap=softcap,
            alibi_slopes=alibi_slopes,
            return_lse=False,
        )
    dq_c, dk_c, dv_c = torch.autograd.grad(out_r, (q_l, k_l, v_l), dout)
    dq.copy_(dq_c)
    dk.copy_(dk_c)
    dv.copy_(dv_c)
    return dq, dk, dv, _softmax_d_varlen(dout, out, batch)


def fwd_kvcache(
    q,
    k_cache,
    v_cache,
    k,
    v,
    cache_seqlens,
    rotary_cos,
    rotary_sin,
    cache_batch_idx,
    cache_leftpad,
    block_table,
    alibi_slopes,
    out,
    softmax_scale,
    causal,
    window_size_left,
    window_size_right,
    softcap,
    rotary_interleaved,
    num_splits,
):
    """Forward with KV cache (inference decode path). Mirrors
    ``flash_attn_2_cuda.fwd_kvcache``.

    Called from ``flash_attn_with_kvcache`` (flash_attn_interface.py). ``k``/``v``
    (optional new tokens) are appended into ``k_cache``/``v_cache`` IN PLACE at
    ``cache_seqlens`` before attending. No backward (matches CUDA).

    ONE batched launch sequence (Phase 3a): the append is a vectorized
    ``index_put_`` and the attention is a single call into the KV-chunked core
    with per-batch ``seqused_k``/``key_leftpad`` masking — no per-batch Python
    loop. Ragged ``cache_seqlens`` are handled by slicing the cache to the
    batch's max post-append length and hard-masking each row's tail (and
    ``cache_leftpad`` head); the bottom-right causal/window diagonal aligns to
    each batch element's *effective* cache length, exactly as if each sequence
    had been sliced out and run alone.

    Returns:
        (out, softmax_lse)
        - out: (batch, seqlen_q, nheads, headdim), dtype of q
        - softmax_lse: (batch, nheads, seqlen_q), float32, +inf on fully-masked rows
    """
    if block_table is not None:
        _unsupported("paged KV cache (block_table)")
    if rotary_cos is not None or rotary_sin is not None:
        _unsupported(
            "rotary embedding inside fwd_kvcache (rotary_cos/rotary_sin)",
            "Apply rotary embeddings to q/k before calling flash_attn_with_kvcache. ",
        )
    batch, seqlen_q, nheads_q, _ = q.shape
    seqlen_cache = k_cache.shape[1]
    head_dim_v = v_cache.shape[-1]
    seqlen_new = k.shape[1] if k is not None else 0
    if k is not None or v is not None:
        assert k is not None and v is not None, "k and v must be provided together"
        assert cache_seqlens is not None, (
            "cache_seqlens is required when appending new k/v to the cache"
        )
    window = _window(window_size_left, window_size_right)

    with torch.no_grad():
        batch_idx = cache_batch_idx.long() if cache_batch_idx is not None else None
        lens = (
            cache_seqlens.long()
            if cache_seqlens is not None
            else torch.full((batch,), seqlen_cache, dtype=torch.long, device=q.device)
        )
        if seqlen_new > 0:
            overflow = lens + seqlen_new > seqlen_cache
            if bool(overflow.any()):
                raise AssertionError(
                    f"KV cache overflow: cache_seqlens={lens[overflow].tolist()} + {seqlen_new} "
                    f"new tokens > cache size {seqlen_cache}"
                )
            rows = batch_idx if batch_idx is not None else torch.arange(batch, device=q.device)
            cols = lens.unsqueeze(1) + torch.arange(seqlen_new, device=q.device)  # (b, s_new)
            k_cache.index_put_((rows.unsqueeze(1).expand_as(cols), cols), k)
            v_cache.index_put_((rows.unsqueeze(1).expand_as(cols), cols), v)
            lens = lens + seqlen_new
        sk_max = int(lens.max()) if batch > 0 else 0
        if sk_max == 0:
            # Nothing visible anywhere: out = 0, lse = +inf (FA2 masked-row sign).
            out_c = q.new_zeros((batch, seqlen_q, nheads_q, head_dim_v))
            lse = torch.full(
                (batch, nheads_q, seqlen_q), _INF, dtype=torch.float32, device=q.device
            )
            return _fill_out(out, out_c), lse
        if batch_idx is not None:
            k_eff = k_cache[batch_idx, :sk_max]
            v_eff = v_cache[batch_idx, :sk_max]
        else:
            k_eff = k_cache[:, :sk_max]
            v_eff = v_cache[:, :sk_max]
        uniform_full = cache_leftpad is None and cache_seqlens is None and seqlen_new == 0
        # Split path (Phase 3b): masked SDPA for out + streaming fp32 lse
        # pass over the effective cache; softcap/ALiBi fall back to the
        # chunked core internally.
        out_c, lse = mps_flash_attn_func(
            q,
            k_eff,
            v_eff,
            softmax_scale=softmax_scale,
            causal=causal,
            window_size=window,
            softcap=softcap,
            alibi_slopes=alibi_slopes,
            seqused_k=None if uniform_full else lens,
            key_leftpad=cache_leftpad.long() if cache_leftpad is not None else None,
            return_lse=True,
        )
        lse = _flip_lse_inf(lse)
    return _fill_out(out, out_c), lse
